default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  host: <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('DB_PORT', 3306) %>
  username: <%= ENV.fetch('DB_USERNAME', 'bid_user') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'bid_pass') %>

development:
  <<: *default
  database: bid_collections_development

test:
  <<: *default
  database: bid_collections_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'bid_collections_production') %>
