default: &default
  adapter: mysql2
  username: root
  password: greendoor1012
  host: localhost
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  database: bid_collections_development

test:
  <<: *default
  database: bid_collections_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'bid_collections_production') %>
